# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Jacob Adkins
email:            jacobpadkins@gmail.com
description:      
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'jpa.io' # The base hostname & protocol for your site
github_username:  jpadkins
twitter_username: JacobPaulAdkins

markdown:  kramdown
permalink: pretty
paginate:  12

gems:
  - jekyll-paginate
#  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
#tag_page_dir:         tag
#tag_page_layout:      tag_page
#tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  jacob:
    name:             Jacob Adkins
    bio:              Computer Science Enthusiast
    gravatar:         http://www.gravatar.com/avatar/85b220f00d20e713a89b9e9ffddb560f?s=300
    email:            jacobpadkins@gmail.com
    website:          jpa.io
    github_username:  jpadkins
    twitter_username: JacobPaulAdkins
